name: Push to Postman Workspace

on:
  push:
    branches:
      - main  # Replace with your branch if different

jobs:
  push-to-postman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Push collection to Postman
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        COLLECTION_ID="28019073-4d760e4f-bc71-4265-bc05-38e0826aa661"

        # Use curl to push the collection to Postman
        curl -X PUT "https://api.postman.com/collections/$COLLECTION_ID" \
             -H "X-Api-Key: $POSTMAN_API_KEY" \
             -H "Content-Type: application/json" \
             -d "{
                   \"collection\": $(< ./path/to/your/collection.json)
                 }"
