name: Push to Postman Workspace

on:
  push:
    branches:
      - main

jobs:
  push-to-postman:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Push collection to Postman
      env:
        POSTMAN_API_KEY: ${{ secrets.POSTMAN_API_KEY }}
      run: |
        COLLECTION_ID="28019073-4d760e4f-bc71-4265-bc05-38e0826aa661"
        
        jq -n --argfile collection postman.json '{"collection": $collection}' | \
        curl -X PUT "https://api.postman.com/collections/$COLLECTION_ID" \
             -H "X-Api-Key: $POSTMAN_API_KEY" \
             -H "Content-Type: application/json" \
             -d @-
