name: Update Postman Collection

on:
  schedule:
    - cron: '0 17 * * FRI'
  workflow_dispatch:
  repository_dispatch:
    types: [update_sdk]

permissions:
  contents: write
  pull-requests: write

jobs:
  update-openapi:
    runs-on: ubuntu-latest

    steps:
    - name: Check out code
      uses: actions/checkout@v4
      
    - name: Download OpenAPI file
      run: curl -sSL -o ./specs/openapi.yaml https://insulator.conductor.one/api/v1/openapi.yaml
      
    - name: Install openapi-to-postmanv2
      run: npm install -g openapi-to-postmanv2

    - name: Generate Postman collection
      run: make generate

    - name: Check for changes
      id: git_diff
      run: |
        git add -A
        if git diff --cached --quiet; then
          echo "has_changes=false" >> $GITHUB_OUTPUT
          echo "No changes detected"
        else
          echo "has_changes=true" >> $GITHUB_OUTPUT
          echo "Changes detected:"
          git diff --cached --name-only
        fi

    - name: Create Pull Request if changed
      if: steps.git_diff.outputs.has_changes == 'true'
      uses: peter-evans/create-pull-request@v5
      with:
        token: ${{ github.token }}
        commit-message: 'Update postman collection'
        title: 'Update Postman collection'
        body: 'This PR updates the regenerates the postman with the latest openapi.yaml'
        branch: 'update-postman'
